### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by vmanikes** [asalih/guardian#13]
I am interested in contributing to this project, how can I contribute?

**Comment by asalih** [comment]
hello @vmanikes thanks for your interest. I've added https://github.com/asalih/guardian/blob/master/CONTRIBUTING.md

As you may notice there is not much test file in the repo I am aiming to increase tests and this is a must of course so in your contribution, the code need to be well tested.

Thank you!

**Comment by vmanikes** [comment]
Will do, thanks bud
